spring:
  datasource:
    url: jdbc:mysql://sql6.freemysqlhosting.net:3306/sql6430901?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Jakarta&useSSL=false
    username: sql6430901
    password: widFFG4cAi
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    database-platform: MYSQL
  flyway:
    enabled: true
    locations: classpath:/db/migration
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
  devtools:
    livereload:
      enabled: true
    add-properties: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true
      location: ${java.io.tmpdir}
  session:
    store-type: none
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 0

#We can use the httpOnly and secure flags to secure our session cookie:
#
#httpOnly: if true then browser script won't be able to access the cookie
#secure: if true then the cookie will be sent only over HTTPS connection
server:
  servlet:
    session:
      cookie:
        http-only: true
#        secure: true

# 1 days = 1 * 24 * 60 * 60
cookie:
  maxAge: 86400
